### PR TITLE
Correct comment information

### PR DESCRIPTION
**Pull request by liumian97**
Correct some comment information

### CODE REVIEW

**Comment by lindzh** [comment]
Very pleased to see your contribution.But could you please create an issue at https://issues.apache.org/jira/browse/ROCKETMQ/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel? And also rename this pull request title, like, [ROCKETMQ-XXX] as the issue id?

**Comment by vongosling** [comment]
@liumian97 if you correct the PR info as @lindzh pointed out, may be a good start for this PR merging:-)

**Comment by dongeforever** [comment]
@liumian97 could you please follow the apache way of PR: create issue and rename pull request

**Comment by vongosling** [comment]
if any update for this pr, we will close it~

**Pull request closed without merging**
