### PR TITLE
Add test case for LocalFileOffsetStore

### PR DESCRIPTION
**Pull request by djKooks**
I'm reviewing code by testing example and looking on test case. I add some test case which is missing in. If it is okay, I'll keep adding on while review. Don't hesitate to tell me if there is other rule about adding tests.

### CODE REVIEW

**Comment by zhouxinyu** [comment]
Hi, @djKooks 

We would appreciate your any contribution, please feel free to let us know if you have any question.
Some docs may be for your reference:
[1]. http://rocketmq.incubator.apache.org/docs/code-guidelines/
[2]. http://rocketmq.incubator.apache.org/docs/pull-request/

**Comment by djKooks** [comment]
@zhouxinyu Thanks! I'll look on.

**Comment by zhouxinyu** [comment]
LGTM, please @vongosling @lizhanhui help review.

**Comment by lizhanhui** [comment]
+1

**Comment by dongeforever** [comment]
+1. This PR has been merged. @djKooks you may want to close it now

**Comment by djKooks** [comment]
@dongeforever Thanks!

**Pull request closed without merging**
