### PR TITLE
[ROCKETMQ-99] Add scripts for Windows

### PR DESCRIPTION
**Pull request by lizhanhui**
Add scripts for windows where possible.

### CODE REVIEW

**Comment by vongosling** [comment]
@lizhanhui Cool. Did you check the commits, letting all passed in at least 2 windows environment ?

**Comment by lizhanhui** [comment]
@vongosling I plan to install a Windows XP on a virtual machine if there is no feedback from community. Actually, I am hoping someone may test this PR on Windows 10 which covers majority of windows users.

**Comment by vongosling** [comment]
I am hoping someone may test this PR on Windows 10 which covers majority of windows users.
 Show all checks

Yep agreed.

**Comment by vongosling** [comment]
@lizhanhui Done for dev. branch ~ Could you close this PR?

**Comment by lizhanhui** [comment]
All right.

**Pull request closed without merging**
