### PR TITLE
[ROCKETMQ-75] RemotingCommand header decoding swallows exceptions

### PR DESCRIPTION
**Pull request by shroman**
JIRA issue: https://issues.apache.org/jira/browse/ROCKETMQ-75

Added logging on errors.

### CODE REVIEW

**Comment by shroman** [comment]
Looks like there's no reason (and even may be dangerous) to keep `makeCustomHeaderToNet()` _public_. Made it _private_.

Ready for the review.

**Comment by zhouxinyu** [comment]
Hi @shroman ,

IMO, it could be better that one PR/issue one thing, can we move `makeCustomHeaderToNet` to another issue, and make `makeCustomHeaderToNet ()` private will bring some reflection code, I think it's not very reasonable.

**Comment by shroman** [comment]
@zhouxinyu  I agree on moving it to another issue. I will create another PR for that.
As to making the method private, using reflection for testing is safer than making a method public solely for testing, IMO. It is even called by another private method ;)

**Comment by shroman** [comment]
@zhouxinyu I removed the 2nd commit from this PR. Please review it.

So, what shall we do with `makeCustomHeaderToNet()`?

**Comment by vongosling** [comment]
@shroman  since 4.1.0, we will start a new branching model, more formalized, more flexible. All PRs except those hotfixs, we recommended to merge back to develop branch. This guide will publish in website sooner. So, we hope to postpone this PR merge action util 4.0.0 release :-)

**Comment by zhouxinyu** [comment]
LGTM, thanks @shroman , please @vongosling @lizhanhui help review.

**Comment by shroman** [comment]
@vongosling @lizhanhui are you ok with this fix? If yes, I will merge.

**Comment by vongosling** [comment]
@shroman Recently, some our customer resort to us to degrade JDK version to 1.6. IMO, we can keep the pace with netty for our SDK. So, if we polish code associating with SDK, we'd better use JDK 1.6 semantic :-)

**Comment by shroman** [comment]
@vongosling Is it for `rocketmq-remoting` only or for the whole project?
It doesn't sound exciting to go back to old JDKs, but ok :)

**Comment by lizhanhui** [comment]
Agree, for the client related module, I think it's best to have maximum compatibility as many application developers are still working on legacy systems.

**Comment by shroman** [comment]
@lizhanhui which modules in RocketMQ are 'client-related'? to be aware when changing the code.

Ideally, it would be nice to split the client-related code with what we are doing at Apache. Just my thoughts.

**Comment by lizhanhui** [comment]
@shroman client/common/remoting

Frankly speaking, it's kind of dilemma. pom.xml has already defined Java language version to 1.7 and JREs under 1.7 are no longer maintained by Oracle and other vendors; But the reality is many application developers are stilling working on legacy systems which requires Java 1.5, 1.6.

**Comment by shroman** [comment]
@lizhanhui @vongosling I see. I changed the code, please have a look.
Also, I will try to keep the modules in mind, but we need something not to forget they have to be treated differently from others. Can't propose any clean solution now.

**Comment by vongosling** [comment]
LGTM :-) We will degrade the client SDK version to 1.6 in the developer branch

**Comment by lizhanhui** [comment]
Looks good.

**Comment by vongosling** [comment]
cool~

**Pull request closed without merging**
