### PR TITLE
注释

### PR DESCRIPTION
**Pull request by liucyu**

### CODE REVIEW

**Comment by vsair** [comment]
Thanks for your contribution, but please read the contributor's guide first. Then, you would,

1. Create an jira issue, and rename the pr's title and description.
2. Chinese is not allowed in code.

**Comment by vongosling** [comment]
@liucyu If no update for this PR, we will close it.

**Comment by lindzh** [comment]
As RocketMQ is widely use all over the world,I think there is no need to add chinese comment.I suggest add a blog for source code reading.

**Comment by goodchax** [comment]
是否支持事务消息？

**Pull request closed without merging**
