### PR TITLE
[ROCKETMQ-35] Consumer client can’t persist consume offset table to Broker

### PR DESCRIPTION
**Pull request by qinliujie**
https://issues.apache.org/jira/browse/ROCKETMQ-35

### CODE REVIEW

**Comment by zhouxinyu** [comment]
It's a bug indeed, thanks @qinliujie . Please @vongosling  @lizhanhui  review.

**Comment by vintagewang** [comment]
review ok

**Comment by zhouxinyu** [comment]
@qinliujie , I can't find your Github email from https://github.com/qinliujie, could you please provide it for me which is need in merge process.

**Comment by qinliujie** [comment]
@zhouxinyu I have edited my profile,you can look again.

**Pull request closed without merging**
