### PR TITLE
add telnet CMD to nameServer 

### PR DESCRIPTION
**Pull request by Ah39**
telnet Nameserver 9875 port
for example  telnet 192.168.186.131 9875

****************************************************
Welcome . CMD for example 
1. consumerProgress -g zzHelloSubGroup 
2. consumerConnection -g zzHelloSubGroup 
3. producerConnection -t zzHello -g zzHelloSendGroup 
4. topicStatus -t zzHello 
****************************************************
topicStatus -t zzHello
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
broker-a                          0     0                     20                      2017-03-03 16:19:36,904
broker-a                          1     0                     19                      2017-03-03 16:19:36,916
broker-a                          2     0                     18                      2017-03-03 16:00:37,802
broker-a                          3     0                     18                      2017-03-03 16:00:37,813

### CODE REVIEW

**Comment by Jaskey** [comment]
Please notice your pr topic and relate the JIRA in the descriptions.

**Comment by Ah39** [comment]
https://issues.apache.org/jira/browse/ROCKETMQ-117

**Comment by vongosling** [comment]
@Ah39 Could you modify your PR topic?  http://rocketmq.incubator.apache.org/docs/pull-request/,please refer to it ~

**Comment by Ah39** [comment]
here is the new https://github.com/apache/incubator-rocketmq/pull/81

**Comment by Jaskey** [comment]
@Ah39 ， do you create a brand new pr with the same issue, if so IMO, this pr can be closed and let's review the pr of #81

**Comment by vongosling** [comment]
if any update for this pr, we will close it~

**Pull request closed without merging**
