### PR TITLE
We need flink-rocketmq-connector

### PR DESCRIPTION
**Pull request by artJava**

### CODE REVIEW

**Comment by vongosling** [comment]
Some guys are engaged in this features. thanks @artJava

**Comment by artJava** [comment]
How long do we have to wait?

**Comment by artJava** [comment]
大概需要等多久才会发布新版本呢

**Comment by vesense** [comment]
@artJava Currently, the patch is in the verification phase, and will be released later.

**Comment by adventurer2008** [comment]
**We really need this feature.**

**Comment by vesense** [comment]
@adventurer2008 Sorry for the delay because of my heavy work. Will submit the patch before January 20 (ASAP). Thanks for your patience.

**Comment by adventurer2008** [comment]
Great, Thank you very much. @vesense

**Comment by adventurer2008** [comment]
@vesense , brother, Can we get the patch about flink-rocketmq-connector?

**Comment by vesense** [comment]
@adventurer2008 I need to add some documents for this module, after that I will commit it.  All of the things can be done in this week. 
As you know, we usually do these tasks on off-work hours. So some unexpected delay might happen, sorry about that.

**Comment by adventurer2008** [comment]
I understand absolutely. Whatever, I apprecaite your effort.

**Comment by vesense** [comment]
@adventurer2008 @Jaxvk I added some documents and code comments. Now the patch is available.  https://github.com/apache/rocketmq-externals/pull/45
Thanks for your patience.

**Pull request closed without merging**
