### PR TITLE
[ROCKETMQ-101]Fix possible NullPointerException when retry in send Async way

### PR DESCRIPTION
**Pull request by Jaskey**
JIRA: https://issues.apache.org/jira/browse/ROCKETMQ-101

### CODE REVIEW

**Comment by lizhanhui** [comment]
This issue is valid and the bug will be triggered under the following conditions:
1. A target message queue is specified, which will pass null for TopicPublishInfo parameter;
2. Async sending;
3. Retry happens;
4. sendLatencyFaultEnable is enabled(On default, it's not enabled)


The PR, IMO, is not good as it simply disabled promised retry attempts without notice.  Instead of logging retry failure, retry sending should be done against the original chosen broker.

**Comment by Jaskey** [comment]
@lizhanhui , # 4 is not the nessary conditions, since even it is not enble, the tpInfo's method is still used.

            try {
                int index = tpInfo.getSendWhichQueue().getAndIncrement();
                for (int i = 0; i < tpInfo.getMessageQueueList().size(); i++) {
                    int pos = Math.abs(index++) % tpInfo.getMessageQueueList().size();
                    if (pos < 0)
                        pos = 0;
                    MessageQueue mq = tpInfo.getMessageQueueList().get(pos);
                    if (latencyFaultTolerance.isAvailable(mq.getBrokerName())) {
                        if (null == lastBrokerName || mq.getBrokerName().equals(lastBrokerName))
                            return mq;
                    }
                }

                final String notBestBroker = latencyFaultTolerance.pickOneAtLeast();
                int writeQueueNums = tpInfo.getQueueIdByBroker(notBestBroker);
                if (writeQueueNums > 0) {
                    final MessageQueue mq = tpInfo.selectOneMessageQueue();
                    if (notBestBroker != null) {
                        mq.setBrokerName(notBestBroker);
                        mq.setQueueId(tpInfo.getSendWhichQueue().getAndIncrement() % writeQueueNums);
                    }
                    return mq;
                } else {
                    latencyFaultTolerance.remove(notBestBroker);//my npe is thrown here
                }
            } 


Besides, if topic route info is null which propably means user is send through my seletor method, resend should still respect user's seletor, so chosen broker is not enough, the chosen queue is needed, which may be another issue, I guess it is not a very minal effort, since the existing interface does not record any chosen queue info.

**Comment by lizhanhui** [comment]
Yes, #4 is not required as MQFaultStrategy#92 may also generate NPE.
Queue ID info is contained in the request header, minimal effort suffices.

**Comment by Jaskey** [comment]
@lizhanhui , please review the updated pr

**Comment by lizhanhui** [comment]
Looks good.

**Comment by zhouxinyu** [comment]
Looks good, please @vongosling help review.

**Comment by Jaskey** [comment]
@vongosling @lizhanhui 

This bug is crucial and easy to reproduce which makes send with seletor is  not reliable, when can this pr be merged and release?

**Comment by lizhanhui** [comment]
@Jaskey You are right, I'll follow up and merge this PR ASAP.

**Comment by vongosling** [comment]
LGTM~

**Comment by lizhanhui** [comment]
@Jaskey I'll merge this PR soon. Please close this issue.

**Comment by Jaskey** [comment]
Thank you @vongosling @lizhanhui @zhouxinyu

**Comment by vongosling** [comment]
@lizhanhui @Jaskey we'd better close after merge :-)

**Comment by lizhanhui** [comment]
Merged

**Pull request closed without merging**
