### PR TITLE
[ROCKETMQ-155] fix typo in ClientConfig

### PR DESCRIPTION
**Pull request by vesense**
rename `pollNameServerInteval` to `pollNameServerInterval`

### CODE REVIEW

**Comment by lizhanhui** [comment]
Looks good.

**Comment by vongosling** [comment]
LGTM,please @shroman @lizhanhui help to review it~

**Comment by lizhanhui** [comment]
+1

**Comment by shroman** [comment]
+1

**Comment by lizhanhui** [comment]
This is quick fix of typo and we have collected three +1s. Now it's merged.

**Comment by lizhanhui** [comment]
@vesense Please close this issue at your convenient time.

**Comment by vesense** [comment]
Thanks & Closed.

**Comment by Jaskey** [comment]
We should have a compatibility notice and guide when releasing 4.1.

**Comment by lizhanhui** [comment]
Yes, best to have this change log.

**Pull request closed without merging**
