### PR TITLE
[ROCKETMQ-2] Closing the channel

### PR DESCRIPTION
**Pull request by shroman**

### CODE REVIEW

**Comment by vongosling** [comment]
@shroman Thanks for your PR, Could you paste some unit test for these question :-)

**Comment by shroman** [comment]
@vongosling Thanks for pointing to the checklist. Added the test and more ;)

**Comment by vongosling** [comment]
@shroman 
Thanks for your PR, Could you paste some unit test for these question :-) . please see our contributing checklist, https://github.com/apache/incubator-rocketmq/blob/master/CONTRIBUTING.md

**Comment by shroman** [comment]
@vongosling The unit test is included in the PR. I don't quite understand what else is needed...

**Comment by shroman** [comment]
Changed the title and the description according to the project's PR process.

**Comment by vongosling** [comment]
That's ok for me. please @lollipopjin @zhouxinyu review it.

**Comment by zhouxinyu** [comment]
It seems ok, Thanks @shroman.

**Comment by shroman** [comment]
@vongosling @zhouxinyu Cool!
Btw, have you managed to get admin permissions for JIRA to add guys who send requests to JIRA contributor list? We are working on tickets but cannot assign ourselves and change the progress status ;)

**Comment by vongosling** [comment]
@lollipopjin  your review opinion is ?

**Comment by lollipopjin** [comment]
Seems ok for me.

**Comment by vongosling** [comment]
@shroman  I will try to grant right permission for your :-)

**Pull request closed without merging**
