### PR TITLE
[ROCKETMQ-5] Avoid creating directories in UtilAll#getDiskPartitionSp…

### PR DESCRIPTION
**Pull request by shroman**
…aceUsedPercent()

JIRA issue: https://issues.apache.org/jira/browse/ROCKETMQ-5

### CODE REVIEW

**Comment by shroman** [comment]
@lollipopjin I recreated the pull request. Ready for the review.

**Comment by lollipopjin** [comment]
Great. @vongosling @zhouxinyu  PLZ review the code.

**Comment by vongosling** [comment]
alright for me

**Comment by zhouxinyu** [comment]
Great. Thanks @shroman

**Comment by shroman** [comment]
Thank you, guys. I will close the issue after it is merged then.

**Pull request closed without merging**
