### PR TITLE
[ROCKETMQ-34] Potential NPE in NettyConnetManageHandler#connect

### PR DESCRIPTION
**Pull request by shroman**
JIRA issue: https://issues.apache.org/jira/browse/ROCKETMQ-34

### CODE REVIEW

**Comment by shroman** [comment]
@vongosling @zhouxinyu Easy fix. Please review.

**Comment by zhouxinyu** [comment]
Easy fix indeed, thanks @shroman , please @vongosling @stevenschew review.

**Comment by stevenschew** [comment]
review Ok

**Comment by vintagewang** [comment]
```
        public void connect(ChannelHandlerContext ctx, SocketAddress remoteAddress, SocketAddress localAddress, ChannelPromise promise)
            throws Exception {
            final String local = localAddress == null ? "UNKNOW" : localAddress.toString();
            final String remote = remoteAddress == null ? "UNKNOW" : remoteAddress.toString();
            log.info("NETTY CLIENT PIPELINE: CONNECT  {} => {}", local, remote);
            super.connect(ctx, remoteAddress, localAddress, promise);

            if (NettyRemotingClient.this.channelEventListener != null) {
                NettyRemotingClient.this.putNettyEvent(new NettyEvent(NettyEventType.CONNECT, remoteAddress.toString(), ctx.channel()));
            }
        }
```

Hi, @shroman  is this ` super.connect` dangerous ?

**Comment by vintagewang** [comment]
image


review ok.

**Comment by shroman** [comment]
@vintagewang   `super.connect` can throw NPE when remoteAddress is null, but as far as I see in netty code, it is ok (notification is raised). And the client handles this in `invoke*` methods by `throw new RemotingConnectException(addr);` (for instance, NettyRemotingClient lines 518-519).
To summarize, it looks safe.

**Pull request closed without merging**
