### PR TITLE
[ROCKETMQ-175] Consumer may miss messages because of inconsistent sub…

### PR DESCRIPTION
**Pull request by vsair**
For push mode, update subscription version when rebalance result changed, then send heart beat to broker immediately.

Maybe subscriptions management mechanism could be re-designed to meet more complicated scenarios.

### CODE REVIEW

**Comment by Jaskey** [comment]
Actually missing message can not be avoided when the diffrerent tags are subscribed in the same consumer groups.

Say for two queues q1 q2, two consumers c1 c2.
c1->TAG1
c2->TAGB

when allocating, c1->q1, c2->q2 100 messages are sent to this topic with TAG1.

C2 will recive nothing and c1 will recieve 50 messages. but the consumer offset of q2 is till moving on. Then 50 messages are missing.

**Comment by vsair** [comment]
This PR does't break the restrict that all consumers should have the same subscription. It only focus on broker should hold the online consumer's subscription. Miss messages is just one result caused by inconsistency subscriptions.

**Comment by Jaskey** [comment]
@vsair 
What I mean is that the scene this pr is going to fix is breaking the restrict that the same consumer group has the same subscriptions.

Though this may help improve the refresh the subscriptions, but the same problem is still there remains  no solution in the existing design.

IMO, we should solve this problem directly to solve all the related problem. Which is issued in https://issues.apache.org/jira/browse/ROCKETMQ-94

**Comment by vsair** [comment]
Yeah, you're right. There is no way to solve the problem in existing design.
But the result is : 
when user stop the consumer has diff subscription, broker could hold the correct info.
I also look forward to the solution in https://issues.apache.org/jira/browse/ROCKETMQ-94.

**Comment by dongeforever** [comment]
@Jaskey It may take a long time to fix the issue ROCKETMQ-94.
And we could improve it step by step.
Now one consumer startup will refresh the subscriptions, but the consumer shutdown does not.
This maybe confusing.
IMO, it is reasonable to refresh when rebalance occurs.

**Comment by dongeforever** [comment]
@zhouxinyu @vongosling

**Comment by dongeforever** [comment]
This PR is merged  @vsair

**Comment by vsair** [comment]
OK

**Comment by CoderLan0668** [comment]
so what's the solution for this problem? it's 2019 now, the problem is still on.

**Pull request closed without merging**
