### PR TITLE
[ROCKETMQ-54] Polish unit tests for rocketmq-namesrv

### PR DESCRIPTION
**Pull request by iskl**
[Issue ref link](https://issues.apache.org/jira/browse/ROCKETMQ-54)

This PR is in continuous delivery. About 25% in progress. 

When it's done, I will announce in comment :-)

### CODE REVIEW

**Comment by zmyer** [comment]
review ok.

**Comment by zhouwei198732** [comment]
review ok

**Comment by stevenschew** [comment]
Review Ok

**Comment by stevenschew** [comment]
In the OSX system, the integration test does not pass. We have already dealt with it. Please merge master fetch first and push again. @iskl

**Comment by vongosling** [comment]
All checks have failed, please ensure your testing validity

**Comment by vongosling** [comment]
Could you squash your many commmits

**Comment by iskl** [comment]
I've merged this branch from remote master. The integration test on OSX are all passed. 

Thanks~

**Pull request closed without merging**
