### PR TITLE
[ROCKETMQ-3] Clean up unit tests, remove try...catch, using assertNull etc

### PR DESCRIPTION
**Pull request by dongeforever**
Remove try...catch, using assertNull etc

### CODE REVIEW

**Comment by dongeforever** [comment]
@WillemJiang I am sorry to bother you so many times. A new pr is created for squashing. And I will take care of my commits carefully next time.

**Comment by WillemJiang** [comment]
There is only one line change here after rebasing the codes. I just commit the patch into master branch.

**Comment by vongosling** [comment]
@shroman cool, we will add code-style parts in website. Every guys could comment it and help us to perfect it :-)

**Comment by dongeforever** [comment]
This PR could be closed for the code has been merged into apache master.

**Comment by WillemJiang** [comment]
Please using the mailing list to discuss the code-style issue.

**Pull request closed without merging**
