### PR TITLE
[ROCKETMQ-8] Standardize build script.

### PR DESCRIPTION
**Pull request by lollipopjin**
Step1:
Remove original scripts.

JIRA Issue: https://issues.apache.org/jira/browse/ROCKETMQ-8

### CODE REVIEW

**Comment by vongosling** [comment]
Sorry, we don't merge this PR.
IMO, there is step 2 you must finish :-)

**Comment by lollipopjin** [comment]
@vongosling 
I have finished all steps.

**Comment by vongosling** [comment]
Thanks for your PR.
I have checked it. It's seems ok for me. please @stevenschew @zhouxinyu review it.

**Comment by zhouxinyu** [comment]
It seems ok.

**Comment by stevenschew** [comment]
review Ok!

**Pull request closed without merging**
