### PR TITLE
[ROCKETMQ-234] bugfix - broker will write response twice in batch scenario

### PR DESCRIPTION
**Pull request by evthoriz**
Bug in handle batch response. It will write response twice to client in batch scenario.
Jira: [ROCKETMQ-234](https://issues.apache.org/jira/browse/ROCKETMQ-234)

### CODE REVIEW

**Comment by zhouxinyu** [comment]
@evthoriz thanks, It's a bug indeed, could you please attach a JIRA issue link here and polish the PR title with more details?

**Comment by evthoriz** [comment]
@zhouxinyu JIRA issue attached.

**Comment by dongeforever** [comment]
@evthoriz Great catch.

**Comment by lizhanhui** [comment]
+1 
Nice catch.

**Comment by Jaskey** [comment]
+1.
This is is indeed buggy.

Would you please update the description that how the client behave for this problem so that we make our users clear about this.

IMO, this two results should be exactly the same and only logs can be observed but no factual influence

**Comment by evthoriz** [comment]
@Jaskey From the aspect of client, every batch request would cause printing 2 warning logs. But the further influence is it may damage the performance in high throughput scenario where batch interface would more likely be used, because it wasted netty's IO thread time doing meaningless encoding, decoding and printing logs things.

**Comment by Jaskey** [comment]
@evthoriz please update the jira's discriptions so that the user knows this bug and determine whether they should upgrade

**Comment by lindzh** [comment]
+1
Great! This is indeed buggy.

**Pull request closed without merging**
