### PR TITLE
[ROCKETMQ-76] Expose IntegrationTestBase to be used by other integrat…

### PR DESCRIPTION
**Pull request by shroman**
…ion projects

JIRA issue: https://issues.apache.org/jira/browse/ROCKETMQ-76

### CODE REVIEW

**Comment by shroman** [comment]
@vongosling Ready for the review.

**Comment by vongosling** [comment]
@shroman  since 4.1.0, we will start a new branching model, more formalized, more flexible. All PRs except those bugfix, we recommended to merge back to develop branch. This guide will publish in website sooner. So, we hope to postpone this PR merge action util 4.0.0 release :-)

**Comment by zhouxinyu** [comment]
Please @dongeforever help review this PR.

**Comment by dongeforever** [comment]
Thanks @shroman , it is very useful for other projects'  integration tests.

**Comment by dongeforever** [comment]
@shroman It seems that you could merge this PR now.  And according to new branching model, it is better to merge this to the 'develop' branch

**Comment by shroman** [comment]
@dongeforever Thanks! It seems there are no objections, I will merge it to `develop` branch.

**Comment by vongosling** [comment]
@shroman We'd better merge PR not the same guys. you pull, the other guy merge. @dongeforever Could you help us to merge this PR :-)

**Comment by dongeforever** [comment]
@vongosling OK. I would merge this PR. and @shroman could you help me check the PR: https://github.com/apache/incubator-rocketmq/pull/57

**Comment by lizhanhui** [comment]
> We'd better merge PR not the same guys.
@vongosling Any rational reasoning behind this?

**Comment by shroman** [comment]
@dongeforever Yes, sure. But first please address my comments for that PR.

**Comment by vongosling** [comment]
@shroman @lizhanhui we must keep rigorous and cautious for guys PR. So, I recommend the double interleaved close for PR :-)

**Comment by dongeforever** [comment]
@shroman I have merged this PR. and I will have a review for the PR #57 later.

**Pull request closed without merging**
