### PR TITLE
[ROCKETMQ-117] add telnet server to namesrv

### PR DESCRIPTION
**Pull request by Ah39**
https://issues.apache.org/jira/browse/ROCKETMQ-117

### CODE REVIEW

**Comment by vongosling** [comment]
Have you look through the PR instruction, please follow the other PR topic, modify yours "Rocketmq 117"

**Comment by zhouxinyu** [comment]
Hi @Ah39 ,

I am not sure is this PR a real demand, since we have `mqadmin` tool.

On the other hand, do we have any method to intercept or approve the requests from telnet client, like a hook?

**Comment by Ah39** [comment]
Maybe  the QA and other rd may need the telnet tool. They can not use the mqadmin tool.
They may need know the topic infomation and connection , so telnet is most useful tool

**Comment by zhouxinyu** [comment]
@Ah39 Maybe console is a better tool for QA, and your concern makes sense indeed, let's wait for other committers' thoughts.

**Pull request closed without merging**
