### PR TITLE
ROCKETMQ-214

### PR DESCRIPTION
**Pull request by lqjack**
wrapper the AllocateMessageQueueStrategy with ThreadLocal

### CODE REVIEW

**Comment by lqjack** [comment]
later , i will append junit test to verify the function. 
if you have better solution , please reply.thanks .

**Comment by Jaskey** [comment]
What do you want to fix by setting the allocate strategy as thread local?

**Comment by lqjack** [comment]
yes

**Comment by vongosling** [comment]
if any update for this pr, we will close it~

**Pull request closed without merging**
