### PR TITLE
[ROCKETMQ-178] Fix -p -m options

### PR DESCRIPTION
**Pull request by lizhanhui**

### CODE REVIEW

**Comment by lizhanhui** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself. Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

One of the build failed, anyway to trigger restart the build? I do not have the permission to operate on this repo @vongosling

**Comment by vongosling** [comment]
Any trouble is still ?

**Comment by lizhanhui** [comment]
> Any trouble is still ?

No. It's a trivial change and should have been merged/closed.

**Comment by dongeforever** [comment]
@lizhanhui I want to merge this PR. Could you please resolve the conflicting files?

**Comment by dongeforever** [comment]
LGTM, I will merge this PR

**Pull request closed without merging**
