### PR TITLE
[ROCKETMQ-111] fix possible MQClientException when query message before today

### PR DESCRIPTION
**Pull request by yilingfeng**
JIRA:https://issues.apache.org/jira/browse/ROCKETMQ-111
Using "cal.set(Calendar.HOUR,0);" when query message before today which may result in :  
"org.apache.rocketmq.client.exception.MQClientException: CODE: 208 DESC: query message by key finished, but no message. " 
"HOUR" is used for the 12-hour clock.This will cause the start time of the query message to be greater than the creation time of the message.  
Implemenations:  
Using "HOUR_OF_DAY" instead of "HOUR"."HOUR_OF_DAY" is used for the 24-hour clock.
Is that so?@Jaskey @zhouxinyu

### CODE REVIEW

**Comment by Jaskey** [comment]
Hi @yilingfeng , please modify your PR subject and mention your jira address in the description, you can follow this PR. #5

**Comment by lizhanhui** [comment]
Good catch. 
Looks good to me.

**Comment by vongosling** [comment]
+1

**Comment by Jaskey** [comment]
From java doc, 0 of `HOUR` is representing noon or midnight. 

So this problem exists if we call the method after 12:am, the HOUR will becomes 12 RATHER than 0, which may result in problems.

Good catch and nice job.

FYI:

you could try with different system clock, which will give you different result.

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.DAY_OF_MONTH, 1);
        cal.set(Calendar.HOUR, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);

        System.out.println(new Date(cal.getTimeInMillis()));
        System.out.println(cal.get(Calendar.AM_PM));

**Comment by shroman** [comment]
Good catch. I would add unit tests though ;)

**Comment by yilingfeng** [comment]
Thank you for your detailed and clear explanation. It was very helpful and understandable. @Jaskey

**Comment by zhouxinyu** [comment]
@shroman , this PR will be merged soon, looking forward to your unit tests..😀😀😀😀

**Comment by shroman** [comment]
@zhouxinyu Probably you misunderstood what I meant :) -- this PR needs unit tests. I think it's the responsibility of the person who submitted PR to create them, whenever possible, since it reflects his/her intentions.
@yilingfeng Can you please add unit tests?

**Comment by yilingfeng** [comment]
Ok,I've added a unit test. @lizhanhui @shroman

**Comment by vongosling** [comment]
thanks @yilingfeng . Consider this PR has been merged, we will commit your unit-test in another commit. @shroman  I have a same understand as @zhouxinyu about your unit-test said :-)

**Comment by shroman** [comment]
@vongosling I meant "If I were you, I would ..." :) Anyway, I don't see why this pr can be merged if a unit test can be easily written. I think we have to accept PRs with tests, except for the cases when they cannot be implemented.
Ok, then let's close this pr? and tests can be submitted in another one.

@yilingfeng I have a quick look, and here is what I think.
Better name the file `MessageClientIDSetterTest.java` and have tests for `getNearlyTimeFromID()` etc. instead of implementing another method in your unit test class.

**Comment by yilingfeng** [comment]
Sorry, I’ve modified the unit tests. @shroman

**Comment by shroman** [comment]
@yilingfeng Great :+1:  But let's have a new PR for that, as @vongosling commented above (if I understood it correctly)?

**Comment by yilingfeng** [comment]
What does it mean? @vongosling @shroman

**Comment by zhouxinyu** [comment]
Hi @yilingfeng @shroman , there is no need to open a new PR, the new commit will be merged to `develop` branch directly.

**Comment by shroman** [comment]
@zhouxinyu Thanks for clarifying it! ;)
If we don't want to test the private method too, I am ok with the tests now to be merged.

**Comment by vongosling** [comment]
@yilingfeng Could you close this PR. We have merged this pull request 29 days ago.

**Pull request closed without merging**
