### PR TITLE
[ROCKETMQ-83] Fix quick start, annotate setNamesrvAddr

### PR DESCRIPTION
**Pull request by dongeforever**
Fix quick start, annotate setNamesrvAddr

@zhouxinyu please have a review

### CODE REVIEW

**Comment by zhouxinyu** [comment]
Hi, `quickStart.Consumer` also has the same issue, could you please fix it.

**Comment by lizhanhui** [comment]
Yes, both quickstart.Consumer and quickstart.Producer should have xxx.setNamesrv("XXX") as part of documentation, showing how to set name server list programmatically. My fault to leave them as code.

**Comment by dongeforever** [comment]
@zhouxinyu Consumer is also ok now

**Comment by lizhanhui** [comment]
Could you relocate the line properly and wrap the code using appropriate javadoc, say {@code Code is here;} http://stackoverflow.com/questions/541920/multiple-line-code-example-in-javadoc-comment

**Comment by djKooks** [comment]
It works fine. Thanks!

**Comment by vongosling** [comment]
@lizhanhui This problem let me feel a bit awkward when we double-check the 4.0.0 vote checklist. May be, we need to let example module into integration test

**Comment by zhouxinyu** [comment]
@vongosling  I have created a new JIRA issue for it: https://issues.apache.org/jira/browse/ROCKETMQ-84

**Comment by lizhanhui** [comment]
Agree. All directly executable code should be part of the e2e tests.

**Comment by lizhanhui** [comment]
BTW, should we remove example.transaction.* as this feature is not fully implemented in current release. It does not make sense having orphan examples alone.

**Comment by vongosling** [comment]
Agree

**Comment by djKooks** [comment]
How about make a new PR for https://issues.apache.org/jira/browse/ROCKETMQ-84 and update this one? Becuase title is for ROCKETMQ-83, somebody would be confused.

**Pull request closed without merging**
