### PR TITLE
[ROCKETMQ-59] Change Charset usages in RocketMQSerializable to Rocket…

### PR DESCRIPTION
**Pull request by iskl**
The PR is to resolve [issue-59](https://issues.apache.org/jira/browse/ROCKETMQ-59)

### CODE REVIEW

**Comment by lizhanhui** [comment]
Minor changes, appears OK.

**Comment by zhouxinyu** [comment]
@iskl It could be better if we narrow down `CHARSET_UTF8 ` access modifier to `private` and without `static`, for both `RocketMQSerializable` and `RemotingSerializable`.

**Comment by iskl** [comment]
@zhouxinyu That's really a better solution! I've change the access modifiers to `private` for borh.

Since the CHARSET is used in `static` methods, it could not be modified to non-static.

Please help to review~

**Comment by vongosling** [comment]
alright, thanks @iskl

**Pull request closed without merging**
